# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'SahhaReactNativeExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SahhaReactNativeExample

  target 'SahhaReactNativeExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
